<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Queick.Shared.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Queick.Shared.Domain\Queick.Shared.Domain.csproj" />
    </ItemGroup>

</Project>
